pub const MAX_TRUST_TABLE_SIZE: usize = 10;

pub const INSTRUCTION_DEFAULT: u8 = 0;
pub const INSTRUCTION_UPDATE_ACCOUNT: u8 = 1;
pub const INSTRUCTION_REGISTER_RESOURCE: u8 = 2;
pub const INSTRUCTION_REGISTER_INTENT: u8 = 3;
